# -*- coding: utf-8 -*-
"""__init__.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qdAwX91vsaHu36Zdsd9gtYinV3FhRJVt

hydrostats is an open-source package to work with Brazilian hydrometeorological time series.
"""

__version__ = '0.1.1'

from .hydrostats import DailySerie
from .hydrostats import AnualSerie