# -*- coding: utf-8 -*-
"""dupla_massa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18aBDm3pIzdWM5mWy7D4mt5qt_2tXdIlK
"""

from pandas import DataFrame

def DuplaMassa(estacao_ref: DataFrame, estacao_confiavel: DataFrame, periodo):
  """

  Args:
    estacao_ref:
    estacao_confiavel:
    periodo:
  """
  ...

def main():
  ...

if __name__ == "__main__":
  main()